### ISSUE TITLE
1.7.10 roadmap for Alpha

### ISSUE THREAD

**Issue by Dessix** [DSTech/MPM#15]
- [ ] Installation
  - [x] Minecraft
    - [x] Binaries
    - [x] Libraries
    - [x] Assets
    - [x] Server / Client Jars
  - [ ] Forge
  - [ ] Simple Mod - (Any authors for a mod willing to let us use it, please comment)
  - [ ] Mod with dependencies - (Looking for volunteers, as above)
- [ ] Launching
  - [ ] Basic Minecraft
    - [ ] Client #5
    - [ ] Server
  - [ ] Modded Minecraft
    - [ ] Client
    - [ ] Client with mods grabbed from server wrapper
    - [ ] Server
- [ ] Server wrapper
  - [ ] Hang detection
  - [ ] Configuration sharing with clients

**Comment by Dessix** [comment]
Mini-milestone, unmodded clients and unwrapped servers now launch!
