### ISSUE TITLE
Roadmap for Beta

### ISSUE THREAD

**Issue by Dessix** [DSTech/MPM#16]
- [ ] Non-standard-Minecraft arches
- [ ] Server wrapper
  - [ ] Restart handling and automated backups
  - [ ] Configuration sharing with clients
  - [ ] Hang detection
